syntax = "proto3"; 
// какой синтаксис

package note_v1; // для того, если будет из одного proto файла импортироваться другой

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

// указывает на то, какой пакет будет у сгенерированных пакетов
// github.com/IbadT/go-lang-microservices/week_1/grpc - имя модуля, в котором находимсы
// pkg - то, куда будет генерировать
// note_v1;note_v1 - в папку файл note_v1
option go_package = "github.com/IbadT/go-lang-microservices/week_1/grpc/pkg/note_v1;note_v1";

// создаем сам api 
service NoteV1 {
    // rpc ручка - тк работаем с удаленным вызовом процедур
    // имя endpoint-a 
    // входной параметр
    // return
    // выходной параметр
    rpc Create(CreateRequest) returns (CreateResponse);
    rpc Get(GetRequest) returns (GetResponse);
    rpc List(ListRequest) returns (ListResponse);
    rpc Update(UpdateRequest) returns (google.protobuf.Empty);
    // rpc Update(UpdateRequest) returns (google.protobuf.Empty);
    // возвращают пустоту (пустая структура)
    rpc Delete(DeleteRequest) returns (google.protobuf.Empty);
    // входной и выходной параметр, всего 1, нельзя их изменить 
}

// описание декларации

message NoteInfo {
    string title = 1;
    string content = 2;
    string author = 3;
    bool is_public = 4;
}

message Note {
    int64 id = 1;
    NoteInfo info = 2;
    google.protobuf.Timestamp created_at = 3;
    google.protobuf.Timestamp updated_at = 4;
}

message UpdatedNoteInfo {
    // nullable типы данных если не указать, то будет значение null
    // очень удобно для update, тк не все данные будут заполнены для обновления
    // если null, то не нужно обновлять, если значение, то обновляем
    google.protobuf.StringValue title = 1;
    google.protobuf.StringValue context = 2;
    google.protobuf.StringValue author = 3;
    google.protobuf.BoolValue is_public = 4;
}

message CreateRequest {
    NoteInfo info = 1;
}

message CreateResponse {
    int64 id = 1;
}

message GetRequest {
    int64 id = 1;
}

message GetResponse {
    Note note = 1;
}

message ListRequest {
    int64 limit = 1;
    int64 offset = 2;
}

message ListResponse {
    // возвращаем слайс notes
    // repeated - слайс
    repeated Note notes = 1;
}

message UpdateRequest {
    int64 id = 1;
    UpdatedNoteInfo info = 2;
}

message DeleteRequest {
    int64 id = 1;
}